### ISSUE TITLE
New docstrings parser too strict

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#108]
Whenever it detects something it doesn't like it errors (actually, it raises `Failure` and that's that).
Up to now we'd arranged so that all such errors would be non fatal (i.e. you could print a warning and drop the docstring you don't like, or the part of the docstring).

It'd be nice to recover that behavior, as the current one makes it close to impossible to generate any documentation.

**Comment by trefis** [comment]
Also, things like this:
```
Failure("File \"csvfields/xml-light/dtd.mli\", line 27, characters 26-29:\n'{ul ...}' (bulleted list) must begin on its own line")
```
probably don't need to be *that* strict.

**Comment by aantron** [comment]
[The parser](https://github.com/ocaml/odoc/blob/d4b1b9479eb200a5b67b1e266c4d2423da889a8e/src/parser/parser_.mli#L3) isn't raising `Failure`, it is exactly designed to report local fatal errors in a `result`, and separate warnings, so that surrounding code can drop the docstring, exactly as you suggest:

https://github.com/ocaml/odoc/blob/d4b1b9479eb200a5b67b1e266c4d2423da889a8e/src/parser/parser_.mli#L9

The surrounding code is in too messy a state at the moment to integrate this properly, so it is weakly "forced" to just raise `Failure` for now as a cop-out. That will be fixed "naturally" as that surrounding code takes better shape.

For the other issue, we can add more error recovery to the parser over time. It already has some for the most common errors, so it's just a matter of priority. If this error occurs only once or a few times in the whole [corpus](https://github.com/ocaml/odoc/blob/d4b1b9479eb200a5b67b1e266c4d2423da889a8e/src/util/corpus.sh) of OCaml docs, then it's probably easier to fix the source of the project than to push back other tasks in odoc and also make the parser more complex in the long term.

**Comment by aantron** [comment]
I suppose the new parser can temporarily be wrapped in a couple lines of code that convert a fatal error into a warning, and return empty docs in an `Ok` result, as a temporary measure to play nice with the surrounding code until it is ready.

**Comment by avsm** [comment]
For development purposes, I find it very convenient to have the strict mode, so that new comments begin well-formed.  Hopefully we can retain that strict mode even if some of them become warnings in the future (similarly to `jbuilder build --dev`).

**Comment by trefis** [comment]
> For development purposes, I find it very convenient to have the strict mode, so that new comments begin well-formed. Hopefully we can retain that strict mode even if some of them become warnings in the future (similarly to jbuilder build --dev).

What we do at jane-street is that we have octavius (the previous version of the comments parser) embedded in a style checking ppx.
That way we always get the errors when building the code, not just when we try to generate documentation (which people rarely do themselves).

That is very convenient and, when it's ready, it would be nice (I'd go as far as to say "necessary") to also have the new parser available as a separate library / package, to maintain that workflow.

**Comment by avsm** [comment]
> That is very convenient and, when it's ready, it would be nice (I'd go as far as to say "necessary") to also have the new parser available as a separate library / package, to maintain that workflow.

Yes, this sounds very useful to have.  Is the style checking ppx on GitHub anywhere? I'm curious what else you check aside from the doc comments.

**Comment by trefis** [comment]
The ppx is there: https://github.com/janestreet/ppx_js_style
Some more style checks or done separately; I think @mbarbin might be working on a unified approach to style checking and might have a few things to add.

**Comment by aantron** [comment]
On a technical level, I think the parser is ready for this now. What it is missing is a lot of experience and feedback from running it on real inputs, so we can tweak which errors are warnings, and otherwise fine-tune it. I did run it on about 80% of packages from opam, though, to get a decent starting point, and to make sure permissive mode deals fairly reasonably with "most" real inputs that are already out there.

The parser works as @avsm described, where it runs in a permissive mode, and reports dubious markup as warnings, except for things it cannot (perhaps currently) recover from. Those are reported as errors. A strict mode treats warnings as errors. The idea is that we make strict mode the default for "private" use during development, but use permissive mode when compiling docs in centralized CI, doc deployments, etc. Individual developers can also use permissive mode if they have a lot of legacy docs not worth fixing up.

It will be easy to extract the parser to a separate library. It is now packaged as a separate Jbuilder sublibrary of odoc, so we would just have to extract that, plus a couple of files from the "model" sublibrary that declare data types.

**Comment by aantron** [comment]
No, I will post when I have some, though.

**Comment by aantron** [comment]
@trefis, The original issue about the parser raising `Failure` and stopping processing of an entire file because of one comment was fixed in 65def8a718c8861af5446496503f90d26084bc4b, "Unconditionally treat parser errors as warnings," linked above. The parser now writes errors to STDERR, emits an empty comment, and continues to the next comment in the file. The overall error handling needs more work, however, but I don't think its remaining shortcomings have a direct effect on this issue. I am working on error handling next.

Separately, the parser is still pretty strict. I see your comment about lists, and will fix that error by turning it into a warning, since that's easy to recover from. There are certainly more such issues. Can you point me to some of the codebases, besides `csvfields`, that you would like to apply odoc to, so I can run odoc against it myself, working through whatever odoc reports? I imagine Base is in that list. The errors will be revealed "progressively," since the parser stops at the first error within one comment that it cannot recover from, so as I add more recovery, I will find more such errors. So, it wouldn't be fair to your time to ask you to successively report them.

**Comment by trefis** [comment]
Thanks for the update!

I think a reasonable starting point would be to clone all of the repository under the janestreet organisation into a single workspace, then do a single build of all of them (+ their dependencies? e.g. ctypes) with dune (the actual build might take some time, but fwiw you should only need to do it once...), and then ask dune to build the doc for all of them.
Hopefully you'll get some errors that way.

Once that passes, I can resume trying to run odoc's master on our internal codebase.

**Comment by jonludlam** [comment]
I believe this is now fixed. @trefis could you please confirm?

**Comment by trefis** [comment]
I think that's right.
I'll try running odoc master on the entirety of our codebase and report back.
