### ISSUE TITLE
Restore support for {%...%}, perhaps with a warning

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#112]

**Comment by rizo** [comment]
Hi @aantron! :)

Sorry I might be missing some context but can you explan the motivation behind this? In particular what’s the status of `{%html: ... %}` as implemented by odoc and why does it require a “warning”?

**Comment by dbuenzli** [comment]
There's a bit of discussion [there](https://github.com/dbuenzli/odig/issues/35).

**Comment by aantron** [comment]
@rizo, odoc `master` doesn't have `{%...%}`, and I guess the main rationale was that we should find alternative mechanisms for most cases where people would want to use `{%...%}`.

**Comment by aantron** [comment]
There is no technical difficulty in putting it back.

**Comment by rizo** [comment]
I'm currently working on an extension to the HTML tree generated by `odoc` and having the ability to embed custom components (like the once mentioned in the documentation thread on http://discuss.ocaml.org) is crucial.

Right now I'm not relying on `{%...%}` because of this particular issue and use lambda-soup to post-process the generated HTML and also inject a some JS to do DOM manipulation (WIP example: <http://odis.io/doc/order/>).

**Comment by aantron** [comment]
@rizo, `{%...%}` will be restored.

The docs look really nice. I'd like to upstream a lot (all?) of your changes into odoc (this is part of the reason to frown on `{%...%` :p). I think PRs to do this would be very helpful, alternatively, can you link to the Lambda Soup postprocessor you are using?

**Comment by rizo** [comment]
@aantron Good to know `{%...%}` is staying! I think this shouldn't prevent the addition of smaller scoped features like markup for images, though.

I'm glad you like it! :) The implementation I referred to is very hacky (it wraps odoc's pages with an iframe... 😱), I'm finishing a cleaner version now and will share it in the next couple of days. We can review it and I'll start submitting PRs.

**Comment by aantron** [comment]
Great, thank you! GitHub needs a scream reaction :p
