### ISSUE TITLE
Modules listed three times for LLVM documentation

### ISSUE THREAD

**Issue by Kakadu** [ocaml/odoc#1186]
I did `odig doc llvm ` for LLVM bindings 16x and 17.x and toplevel modules a listed three times with the same content.
I don't know if this is an issue of LLVM package or odoc itself? Could somebody double-check?

**Comment by dbuenzli** [comment]
It's likely more an `odig` issue so I'm moving the issue there. 

But can you be more specific? In general when this happens it's because you have library variants or something like that. Perhaps the simplest is not to rely on `odig`'s automatically generated file and add your own `index.mld` landing page.

See the docs [here](https://erratique.ch/software/odig/doc/packaging.html#odoc_api_and_manual) for the details.

**Comment by dbuenzli** [comment]
Mmmh it seems I can't transfer stuff to another organisation.
