### ISSUE TITLE
Support running examples in the browser

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#122]
This probably only makes sense in some cases, as some projects will have serious native dependencies. However, for many, it should be possible to run examples in the browser with BuckleScript.

cc @jaredly

**Comment by lpw25** [comment]
I might suggest js_of_ocaml as well/instead of bucklescript because it doesn't require a separate compiler (and so avoids build system issues) and it works with recent versions of OCaml.

**Comment by jaredly** [comment]
We'll certainly want to support both.

**Comment by pmetzger** [comment]
I presume some of the support for this can be stolen from docre?

**Comment by aantron** [comment]
I haven't looked into yet, but I would assume so, to some extent.

I understand the docre implementation requires BuckleScript installed when you build docs (could be wrong). I don't know if we'd want to vendor it in, or something like that.

If using js_of_ocaml, we would also need to have it installed, or vendor it in.

**Comment by lpw25** [comment]
I don't know whether to mention this on this issue or one of the other similar ones (e.g. #128) but one thing that requires some careful thought with these kinds of features is the fact that odoc needs to be runnable on the *installed* contents of a library rather than its *source* directory. This is how `odig` works and is also probably the only way to implement `docs.ocaml.org` without requiring everyone to use `dune`. That shouldn't prevent any of these features being implemented, it just means that you need to provide users with a specification of what you expect to be installed where in order to make these features work -- and ideally update at least `dune` to do the right thing by default.

For example, for running examples using js_of_ocaml you might require that a `.cma` file with the same name as the package be installed in the package's directory (which, whilst standard practice, is not actually required by any other OCaml tooling) that way `odig` could pass the `.cma` file to `odoc` when we ran the `compile` step. That's just off the top of my head -- I really just wanted to make sure people were thinking about this aspect early in the design process.

**Comment by bobbypriambodo** [comment]
Just in case anyone is not aware yet, OCaml (through BuckleScript) is supported by [Klipse](https://github.com/viebel/klipse), an online in-browser evaluator for interactive code snippets. See [this neat article about integrating Klipse+OCaml on your blog](http://blog.klipse.tech/ocaml/2017/10/05/blog-ocaml.html). It supports Reason too.

I imagine that since odoc supports raw HTML, integrating Klipse is a matter of copy-pasting the css and scripts to your ocamldoc comments.
