### ISSUE TITLE
LaTeX/math support

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#123]
- [ ] Support LaTeX syntax, probably in `{%latex: ... %}`.
- [ ] Generate images or use MathJax for HTML output.
- [ ] Alternatively, support replacement text using some to-be-determined syntax.

cc @mars0i @dbuenzli @octachron

**Comment by Octachron** [comment]
My opinion is that MathJax is a good first target, it works quite well in practice; and going further would take a lot of effort.

**Comment by nilsbecker** [comment]
hi, in owl the current situation is that sphinx is used to generate html documentation, and math latex markup is added to the .mli in the forms
```
something bla bla :math:`\exp(x)`
```
for inline math and 
```
.. math::
  \exp(x)
```
for display math. there is an intermediate step where .rst files are generated from the .mli. so it' seems possible that one could have a different markup `{%latex }` which works for odoc directly and converts that to the format required for sphinx, in order to support both documentation generation pipelines from the same .mli

it would be important to not make the .mli markup too verbose. i would consider `{%latex $f(x)$}` with added math environment already too verbose, in particular for inline math.

**Comment by nilsbecker** [comment]
ps. in my experience from scientific journal websites, mathjax is an enormous improvement over embedded latex-generated .png snippets. it works really well most of the time.

**Comment by wusunlab** [comment]
[KaTeX](https://katex.org/) would be even better, since it is much faster than MathJax!

Just wanna provide my two cents. I think an easy (but kinda hackish) way to implement this could be to allow a custom html header file that defines KaTeX (or MathJax if you like) functions to be appended to each generated `index.html` file.  I learned this trick from an example showing how to render math with KaTeX in `rustdoc`: https://docs.rs/rustdoc-katex-demo/0.1.5/rustdoc_katex_demo/ (don't worry if you don't speak Rust; the example has no Rust code involved).

I managed to reproduce it for `odoc` generated html documentation and I got the equations and inline math rendered correctly. But I had to run a bash script to append the KaTeX snippet to each `index.html` after `dune build @doc`.   However, if `odoc` can somehow support the addition of a custom html header then it could be done nicely without any additional command to be executed.

**Comment by mseri** [comment]
Ping here. What would we need to do to get this item moving forward?

**Comment by dbuenzli** [comment]
Design at the ocamldoc language level.

**Comment by mseri** [comment]
Issue, unstable yourself!

I think this is an issue that deserves to be solved :)

**Comment by aantron** [comment]
The meta-issue is we won't have labor available to solve it for the foreseeable future, so we'd like to close the issue to keep the tracker tidy. We may revisit at some future date. Tthe stale label helps to keep track of issues may be worth resurrecting at a better time, should it ever come :)

**Comment by mseri** [comment]
Yeah I know the drill, we are doing it on opam-repository as well. I was asking to keep it open even if there is no workforce available (also, once the changes by Jon and Drup will land, I may have some time to work of it if needed).

**Comment by dbuenzli** [comment]
Well `opam-repository` is another business with issues related to personal setups that may happen to be transient, auto-closing after a while makes sense.

I don't think it's nice for the people who took time to file issues and propose designs to close their issues via bots in this tracker. There are quite a bunch of issues (or let's rather say *ideas*) that deserve to be closed here (and should have been for a long time) to give the project a bit of direction but this issue is certainly not one of them. 

I removed the `stale` label.

**Comment by mseri** [comment]
Thanks!

**Comment by scemama** [comment]
I have been using the following plugin to include LaTeX equations with ocamldoc :

http://akabe.github.io/odoc-ltxhtml/ 

It could be a good starting point to include this feature in odoc.

**Comment by mseri** [comment]
I still think it is worth to keep this open

**Comment by giltho** [comment]
> Design at the ocamldoc language level.
(@dbuenzli)

Could you give me some quick pointers as to how to do this?
I'm guessing it's [in there](https://github.com/ocaml/ocaml/tree/trunk/ocamldoc) and that I'd need to extend the syntax but before that:
- People would need to decide on the markup for latex block and there doesn't seem to be a consensus for `{%latex }`
- There's already syntax for latex, but it's not really for latex ([type decl](https://github.com/ocaml/ocaml/blame/trunk/ocamldoc/odoc_types.ml#L47), [lexer](https://github.com/ocaml/ocaml/blob/trunk/ocamldoc/odoc_text_lexer.mll#L143), [parser](https://github.com/ocaml/ocaml/blob/trunk/ocamldoc/odoc_text_parser.mly#L167) and [documentation](https://ocaml.org/manual/ocamldoc.html#sss:ocamldoc-target-specific-syntax)). i.e. it's a syntax for target-specific blocks (not teaching you anything here). But it means that using `{%latex }` will be extremely close to `{%latex: }`, and therefore very confusing for users

**Comment by dbuenzli** [comment]
> Could you give me some quick pointers as to how to do this?

Well [here's](https://ocaml.org/manual/ocamldoc.html#ss:ocamldoc-formatting) the language, design something that fits :-)

Here's an idea:

* `{%math: … %}` for a math block.
* `{m inline-text}` for inline math. 

Regarding implementation you are looking at upstream's `ocamldoc` implementation. You want to look at making changes to [this parser](https://github.com/ocaml-doc/odoc-parser).

**Comment by giltho** [comment]
Ok, I was implementing something in the parser and realised that it maybe doesn't make much sense, and introduces some redundancy. Would it work to simply introduce a special target to the [target specific formatting](https://ocaml.org/manual/ocamldoc.html#sss%3Aocamldoc-target-specific-syntax) called `math`, and therefore have `{%math: ...%}`  already working out of the box in the parser?
Then, it gets decided that each generator can decide on how to render these targets. Html uses KaTeX, LaTeX keeps it raw.

**Comment by jonludlam** [comment]
I think we can close this now :-)

**Comment by dbuenzli** [comment]
Indeed! Adding a line about the support in https://github.com/ocaml/odoc/blob/master/doc/ocamldoc_differences.mld would be nice though.
