### ISSUE TITLE
Substitution doesn't handle includes

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#13]
Click the `Ord` argument here http://docs.mirage.io/odoc/asetmap/Asetmap/Set/index.html

**Comment by dbuenzli** [comment]
This was generated as follows (`opkg cache clear asetmap; opkg odoc asetmap -v -v`) : 
```
opkg: [EXEC:55939] ['odoc' 'compile' '-I'
                    '/Users/dbuenzli/.opam/4.03.0/lib/ocaml/' '--pkg'
                    'asetmap' '-o'
                    '/Users/dbuenzli/.opam/4.03.0/var/cache/opkg/cache/asetmap/asetmap.odoc'
                    '/Users/dbuenzli/.opam/4.03.0/lib/asetmap/asetmap.cmti']
opkg: [227ms] Compiled odoc files of asetmap
opkg: [EXEC:55940] ['odoc' 'html' '-I'
                    '/Users/dbuenzli/.opam/4.03.0/var/cache/opkg/cache/ocaml/'
                    '-o' '/Users/dbuenzli/.opam/4.03.0/var/cache/opkg/odoc'
                    '/Users/dbuenzli/.opam/4.03.0/var/cache/opkg/cache/asetmap/asetmap.odoc']
```

**Comment by trefis** [comment]
The links are set up correctly, it's just that doc-ock fails to expand the `S with type elt = Ord.t` part because it's naively looking for a `type elt` declaration in `S` while `elt` in this case actually comes from the `include Set.S`.

**Comment by trefis** [comment]
I applied a semi-fix: instead of failing in the case previously described expansion will now behave as if everything was fine. So we now have an expansion for `Make` in the example linked, and the links are not broken anymore.

A proper fix is to modify expansion to handle includes properly, so that in the expansion of `Make` (and not of `S`) replace `include Set.S` by `include Set.S with type elt = Ord.t and type t = Set.Make(Ord).t` and that in the expansion of the include it replaces `type elt` by `type elt = Ord.t`, etc.
This is however more involved and not strictly necessary for a first/beta release, also I expect it will be easier to do when we rewrite the expansion pass. So I'm leaving this issue open but removing the important label.

**Comment by dbuenzli** [comment]
I'm not sure exactly what was the problem but I suspect this is fixed. At least I can click on `Ord` here: 

https://b0-system.github.io/odig/doc/asetmap/Asetmap/Set/index.html
