### ISSUE TITLE
Equivalent of OCamlDoc's `-keep-code`?

### ISSUE THREAD

**Issue by smondet** [ocaml/odoc#164]
Linking value to a rendering of their implementation was nice for learning purposes with `ocamldoc` :)

**Comment by aantron** [comment]
I wonder if we can tell odoc about sources in GitHub somehow.

**Comment by rizo** [comment]
If we report the location of the implementation it should be possible to construct the GitHub link, right?

**Comment by aantron** [comment]
Yep. Unfortunately, we might often have only the location of the interface immediately available. We can probably guess the location of the implementation, but we might need build system support for the general case.

I haven't looked at what's in `.cmti` files in detail lately, so perhaps this is wrong.

**Comment by lpw25** [comment]
I think it would be better to add support for including the source in the documentation. It's nice to have stand-alone documentation that works offline. GitHub links need to be to the right tag and can get out of date. And of course not everyone uses GitHub.

It wouldn't be hard to add an option to specify the `.ml` file in the call to `odoc` and then copy it over to to the html folder. From there you can steadily improve the output -- adding some html around it with code highlighting, adding support for linking to the right line, eventually adding links from identifiers in the code back to the documentation, etc -- as and when people have time to improve it.

If you do add GitHub support it would definitely be better to have the user/build system pass the right information to `odoc`, rather than trying to guess where things are. Heuristics for that are probably going to be wrong as often as they're right.

**Comment by smondet** [comment]
@github-actions I think this still a valid feature request :)

**Comment by brendanzab** [comment]
Would this include links to the source code from the documentation? I find this really useful in other documentation tools, for example in rustdoc and haddock.

Note how [each definition in haddock](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-List.html) has a “# Source” link. Also how [each definition in rustdoc](https://doc.rust-lang.org/std/vec/struct.Vec.html) has a “Source” link.

**Comment by dbuenzli** [comment]
This is being worked on in https://github.com/ocaml/odoc/pull/909

**Comment by dbuenzli** [comment]
I didn't follow what happened in #909 but can't this be closed now ?

**Comment by panglesd** [comment]
Yes!

**Comment by dbuenzli** [comment]
Bravo!
