### ISSUE TITLE
Fix or remove `odoc compile-targets`

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#172]
Somehow it seems it didn't evolve with the corresponding `odoc compile` command (`-o` is still a required argument and a directory in `compile-targets`). 

Unless it is envisioned for `odoc compile` to produce multiple outputs in the future I'd move on to simply remove the command.

**Comment by ostera** [comment]
@aantron, is this what were aiming for with #137 ?

I'd vote for removing `compile-targets` if the same workflow can be orchestrated from outside `odoc` until that issue/thread converges.

If #137 converges into the proposed `odoc build`, then this command isn't needed anymore.
If #137 converges into driving `odoc` from the outside, this command isn't needed either.

**Comment by lpw25** [comment]
I would argue for fixing rather than removing. You need to have `compile-deps`, `html-deps`, and `html-targets` -- so I think it is more consistent to have `compile-targets` even if it is currently trivial to for the build system to know what will be produced by a particular call to `compile`. Besides we may one day want to change or add more outputs to `compile` and if build systems use `compile-targets` then they should be future proof to such changes.
