### ISSUE TITLE
Pretty-print the HTML output

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#187]
This is a bit tricky, because, e.g., `<em>foo</em>bar` cannot be indented, as a newline around `</em>` will be treated as a word break. So, the pretty-printer needs to be aware of the meaning of whitespace in various kinds of HTML tags.

The code for this probably belongs in Markup.ml or TyXML.

cc @ostera @Drup

**Comment by Drup** [comment]
My vote would tend to go to Markup, since this is about the *syntax* of HTML, which is already Markup's territory, while tyxml is more about the semantics. The frontier between the two is occasionally loose in HTML though. 

Additionally, people have asked me about streaming HTML printers for tyxml, and I think it would be better to solve that in Markup once and for all.

**Comment by ostera** [comment]
I actually think that _some_ indentation is already infinitely better than having the output mangled.

But we don't necessarily need fully fledged pretty printing.

**Comment by aantron** [comment]
We can use Markup.ml's pretty-printer after its next release (see aantron/markup.ml#39).
