### ISSUE TITLE
[BuckleScript] Automatic namespacing breaks linking of modules

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#209]
BuckleScript will by default do automatic namespacing of every module when compiling down `.cmt[i]` files, using the `npm/bsconfig` package name as a _suffix_.

I.e, if the package name is `BsReactNative`, and the module name is `ActivityIndicator`, the compiled `.cmti` file will be `ActivityIndicator-BsReactNative.cmti`.

Personally, I do my namespacing by hand, but a lot of people have it set up by default, which means that they can't really reference modules like `ActivityIndicator` above since they don't seem exist. What's worse, the suffixed name is _not a valid OCaml module name_, so it can't be referenced either.

In fact, [bs-react-native](https://github.com/reasonml-community/bs-react-native/) has been experiencing this, as shown in https://github.com/reasonml-community/bs-react-native/pull/259.

What I suggest is fixing this at the boundaries of `odoc/bsb`: the running script for `odoc`, as published by the npm package, could fix this by moving a few things around (i.e, copying and renaming .cmti files before running).

Alternatively, we could consider a `--namespace-suffix` flag that, if present, would strip the suffix from the file name when it builds up the compilation unit.

cc/ @aantron @rizo @grabbou

**Comment by lpw25** [comment]
Before rushing in with a feature like `--namespace-suffix` could we have some description of what Bucklescript is actually doing to implement namespacing? It sounds to me like the currently proposed solutions are basically undoing Bucklescript's namespacing -- so that you'll get conflicts if you try to generate documentation for multiple Bucklescript libraries that have modules with the same name.

Note that dune does namespacing of OCaml modules and odoc is able to correctly handle that without adding ad-hoc features that diverge from OCaml's semantics.

**Comment by ostera** [comment]
@lpw25 good insight! I’ll try to get a word from @chenglou / @bobzhang and see if there’s a way for BuckleScript to do their namespacing like dune does, and how and why they diverge.

**Comment by ostera** [comment]
I recently learned in a discussion with @bobzhang that the reason to do suffix-namespacing is so that the generated .cmt[i] files are __purposefully__ not valid OCaml names.

This means you can't import an "internal" module, such as `ActivityIndicator-BsReactNative` because well, it's not a valid OCaml module name. Instead, you're forced to use it through the name of the package: `BsReactNative.ActivityIndicator`.

I'll explain more in a PR to BuckleScript that I intend to open tomorrow. Will backlink here.
