### ISSUE TITLE
Investigate supporting multiple compilers in a single odoc binary

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#215]
Opening this from a discussion in #214 to make sure it doesn't get lost.

**Context.**

> @ostera:  I've been thinking about this and I think the approach I'd like best would be an odoc release that understands several compiler versions (so you only need one for every compiler), but I might be missing some underlying complexity of developing/building/distributing such a binary. [-> link to comment](https://github.com/ocaml/odoc/pull/214#issuecomment-428758002)

> @rizo: The ability to work with cmt/cmti/cmi files produced by different compiler versions is currently hard because of inconsistencies across typed parsetrees. We would need a typed version of ocaml-migrate-parsetree which doesn’t exist AFAIK. The ad-hoc approach would be too painfull. [-> link to comment](https://github.com/ocaml/odoc/pull/214#issuecomment-428773957)

> @aantron : odoc already has enough code to load Typedtrees from compiler versions 4.02-4.07, and
> largely convert them into its own representation. (src/model).
>
> This leaves the remaining direct uses of Typedtree. Typedtree is used only in the loaders themselves cmt.ml, cmti.ml, and ident_env.ml. That's where (almost?) all of our conditional compilation is, too, but it doesn't look too bad.
>
> It may be possible to link loaders for all OCaml versions into a single odoc binary, and reconcile them somehow. The big issue would be how to avoid duplicating the vast majority of the shared code. Perhaps we can do it with a functor or some preprocessing. We would also likely need to vendor a copy of the relevant files in compiler-libs for each version of the compiler. [-> link to comment](https://github.com/ocaml/odoc/pull/214#issuecomment-428776793)

cc / @lpw25 @dbuenzli @trefis @ryyppy

**Comment by dbuenzli** [comment]
That seems to introduce a lot of complexity for little returns in practice; the constraint is easy to maintain if you use a package manager like `opam`. 

Unless the ocaml compiler starts operating in the same way I don't think it's worth spending time on this and I think we should move on to close this.

**Comment by rizo** [comment]
I agree with @dbuenzli.

@ostera @aantron I think you are looking at this problem from a perspective that benefits only the _present_ distribution process for npm/bucklescript, at the cost of introducing complexity into odoc in the long term.

As @dbuenzli suggested this problem doesn't exist in opam because opam is not just a package manager, it's a compiler switch manager. The fact that BuckleScript currently only runs on 4.02 will (hopefully) change in the future and new versions of the base compiler will be adopted more frequently. What will happen then? People will always want to switch between different compiler releases. Will BuckleScript introduce it's own compiler switching mechanism? Will it reuse opam? I hope the latter but, regardless of that, isolated compiler environments will most likely exist.

Thus I suggest for this problem not to be solved in odoc. There's an orthogonal question of whether version agnostic `Typedtree` usage could simplify odoc's source code, but I'm not considering that at the moment.

**Comment by rizo** [comment]
CC @jordwalke, have you thought about this? Are there any plans to support compiler switching for Reason/BuckleScript projects?

**Comment by dbuenzli** [comment]
> As @dbuenzli suggested this problem doesn't exist in opam because opam is not just a package manager, it's a compiler switch manager.

I'm not sure there's any meaning to that; unfortunately `opam`'s devs didn't fully go through dispelling this idea for `v2` due to a lack of careful review and redesign of the UX. An opam switch is simply a (more or less) isolated package install universe and compilers since `v2` are packages.

Your package manager only needs to be able to express version constraints between the odoc package and the compiler package, it doesn't need to be a "compiler switch manager" (whatever that means).

**Comment by rizo** [comment]
Yes, I'm aware that compilers are handled in the same way as packages in `v2`. I was referring to the UX perspective, i.e., the ability to select a compiler version for an isolated environment.

> package manager only needs to be able to express version constraints between the odoc package and the compiler package

I guess in that case odoc can be installed locally for a particular project in the npm world and be constrained to a particular BuckleScript compiler version.

**Comment by ostera** [comment]
Just want to clarify that my main goal with this issue is not to come up with a way of achieving this, but rather to establish a precedent of a discussion.

This will come up in the future and having sound reasoning behind a denial will make it easier to justify other approaches, such as upstreaming compiler switching at the bsb level, for example, or publish several `npm` packages with different bucklescript version constraints, etc.

**Comment by aantron** [comment]
@rizo

> @aantron I think you are looking 

FTR I am not. I should have been more explicit, but my comment was to clarify what the true difficulties with having odoc support all compiler versions are. The common impression of the problem is not accurate for odoc (but accurate for many other projects that might want to rely on Typedtree). That is because odoc already has its own representation, that is close to being the spine of a version-agnostic Typedtree, and odoc needs to perform relatively limited operations on it, while a general solution to a version-agnostic Typedtree would need to support the expression language and support various complexities odoc never needs.

I don't think we should or need to *do* what I described.

I agree with @ostera that it's good to have discussed it.

**Comment by jordwalke** [comment]
Thanks for bringing it up for the record. My main suggestion was to just make there be a decent error when you try to use the wrong version of odoc on incompatible artifacts if people install `odoc` globally via npm.

> CC @jordwalke, have you thought about this? Are there any plans to support compiler switching for Reason/BuckleScript projects?

For Reason-native projects, people can just use opam or esy (both of which model compilers as package dependencies, and can just consume the raw sources from opam). There's no problem there - you'll never get the wrong version of odoc in a project. The question is about people using npm really. Npm has been terrible at use cases where you build from source, or form dependencies on compiler versions - so some kind of prebuilt binaries are a nice gesture. You might be able to make it work with some peerDeps, but it depends on what kind of install approach you recommend. Would you encourage one global `odoc` installation in the global path? Or would it be project-specific dev-dependencies? Either way, peerDeps _might_ get you where you need to be. I'm beginning to think peerDeps were just a copout for having an insufficiently powerful constraint solver, but they might work well enough here.

**Comment by ostera** [comment]
I think is fair to say that we will have to work around compiler versions at the published artefact level. This might as well be something that a tool like `esy` or `duniverse` takes care of.

Closing this now, thanks for the discussion everyone 🙌
