### ISSUE TITLE
Automatically generating section anchors

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#259]
Many section headings are/will be written like this:

```
{1 Foo bar}
```

i.e., without an explicit anchor

```
{1:foo-bar Foo bar}
```

I think it's desirable for odoc to generate good, legible anchors automatically from the heading text "`Foo bar`."

<br/>

This opens several questions:

- How should the anchor be generated? For example, what should be done with whitespace?
- How should anchors be disambiguated? In particular, nested sections are probably likely to have the same heading text. See #186.
- Should anything be done to encourage anchor stability, so that links remain valid?
- How do we ensure heading anchors (auto-generated or not) don't conflict with signature item anchors?

<br/>

Here are some links with precedent:

- ["Auto-generated-ids" in the Asciidoctor manual](https://asciidoctor.org/docs/user-manual/#auto-generated-ids)
- ["Extension: `auto_identifiers`" in Pandoc](http://pandoc.org/MANUAL.html#extension-auto_identifiers)
- [Stringex's .to_url method](https://github.com/rsl/stringex)
- [An interesting discussion on CommonMark](https://talk.commonmark.org/t//115/25)
- GitHub does something for this as well, e.g. ["Using odoc with OCaml" in odoc's own README](https://github.com/ocaml/odoc#using-odoc-with-ocaml)

<br/>

There seems to be a preference for replacing whitespace with `-`. Even the Asciidoctor manual uses this, though the algorithm it describes uses `_` by default.

If we choose `-`, we need to change the new-style reference kind syntax (#90) to not also use dashes, or otherwise come up with a scheme for referring to a section in a reference.

<br/>

Given that auto-generated anchors are likely to be unstable, should we encourage explicit anchoring?

If so, should we emit a warning if an anchor was generated automatically?

And, if so, should we allow suppressing the warning, e.g. `{1:_ Foo}` for "no anchor", `{1:* Foo}` for "generate and don't warn?"

<br/>

Finally, should we simply not generate anchors?

**Comment by trefis** [comment]
My 2 cents:

> Should anything be done to encourage anchor stability, so that links remain valid?

No. People should just manually pick their anchors if they want stability.

> How do we ensure heading anchors (auto-generated or not) don't conflict with signature item anchors?

The same way we disambiguate signature items with the same name?
That is: we could use `label:foo` (or `anchor:foo` or whatever) to distinguish from `value:foo`.

> If we choose `-`, we need to change the new-style reference kind syntax (#90) to not also use dashes, or otherwise come up with a scheme for referring to a section in a reference.

I don't see any reason to break the syntax that was introduced over a year ago and is already in use for some new features for which we could find a non-conflicting syntax.
Also, IIRC at the time we chose `-` for the "new-style reference kind syntax" precisely because:
- it couldn't appear in signature items names
- ocamldoc was refusing to parse anchors containing dashes

I could be misremembering that second point (but I don't think so), or things could have changed since then, so it might be worth checking again.
But, I think we should keep `-` for the disambiguation syntax, and use something else to replace spaces in anchors (we do have a variety of options here).

> If so, should we emit a warning if an anchor was generated automatically?

I would have that warning turned off by default, and give a flag to turn it on. I'm not keen on the special syntaxes.
Also, if we chose to generate anchors, why would someone explicitly ask for some section to not get an anchor?

> Finally, should we simply not generate anchors?

It wouldn't be high on my todo list, but yes, it seems like a nice thing to have eventually.

**Comment by dbuenzli** [comment]
> {1:foo-bar Foo bar}

Note that this identifier is illegal in `ocamldoc`, no `-` are allowed. As @trefis mentions that actually turned out useful for disambiguating the reference syntax.

Regarding automatic identifiers I have mixed feelings about it. While it is useful to be able to link to sections even though the author didn't take care to identify them, the lack of stability defeats a bit the purpose. I have broken many of my own links in markdown documents, it's a chore that there is no syntax in the language to specify an id for them.

Personally I would rather only warn on lack of id and eschew auto-generation altoghether. Maybe limiting the warning to level 1-2 which is IIRC what gets in the toc.

**Comment by dbuenzli** [comment]
> Doesn't really matter what that anchor look like, as long as there is one. In many cases, documentation is generated for a specific version of a library and so the notion of stability is a bit moot (the markup will never change). It only matters for dev versions and as @trefis said, if someone cares, they'll provide their own anchor.

This is a rather limited view point. Like the web `odoc` is a hypertext system that allows to cross reference across documents you might not own. If we want to encourage cross package links and the creation of a well linked and non-broken hypertext I would rather be in favour of a system that entices authors to provide stable identifiers rather than auto generating them.

**Comment by aantron** [comment]
Regarding the choice of `-` for reference syntax, while we are likely to keep it, I would prefer to change it. It seems the outside world has currently more or less coalesced around using `-` as a word separator in anchors. Even if we don't auto-generate such anchors ourselves, I think users are likely to pick `-` when creating anchor labels manually.

As I understood it, the fact that ocamldoc refused to accept `-` in anchors wasn't an argument about the future desirability of using `-` in anchors, which is what we should care about. It was an argument that `-` did not appear in anchors in existing docs written for ocamldoc, so picking `-` for another use would not conflict with anchors. However, by that argument, we could have picked any other symbol for use in reference disambiguation that cannot appear in ocamldoc anchors, such as, say, `#`, or an entirely different syntax (IIRC `[module]Foo` was suggested).

**Comment by nekketsuuu** [comment]
The latest odoc, version 1.5.3, seems to generate section anchors using hyphens. It, however, does not yet allow hyphens for a characters in a cross-reference string.

Therefore, we cannot write a cross-reference like `{{!section:foo-bar}Foo Bar}`. For now, to insert a cross-reference to a section, we must give the section an anchor explicitly, but this breaks the previous anchor position (e.g. the anchor `#foo-bar` will be removed).

This issue has been closed and also the stale label has been removed, but I think we can consider this a bit more. How about:

- Allow hyphens for cross-reference names, or
- Use underscores with auto-generated section anchors?

**Comment by Julow** [comment]
Odoc 2.0.0 will have a new syntax for escaping hyphens in references:

`{!"foo-bar"}`, `{!section:"foo-bar"}`, `{{!section:"foo-bar"}Foo Bar}`

Alternatively, it is possible to define your own anchors:

```ocaml
(** {1:foo_bar Foo bar} *)
```

and reference it with `{!section:foo_bar}`.

**Comment by nekketsuuu** [comment]
I didn't know such usage of double quotes, thank you! It looks like useful but why we need quotes to mention default naming? Is there any reasons why we cannot use hyphens in names?

The alternative method using underscore is also mentioned in my comment and it breaks the previous anchor position.
