### ISSUE TITLE
Improving `external` output

### ISSUE THREAD

**Issue by nikgraf** [ocaml/odoc#275]
@ryyppy and I are currently looking into using odoc (bsdoc) for multiple BuckleScript projects.

As an example I generated docs for ReasonReact. See a preview below.

I'm wondering what would be the best course of action:
- Should we simply ignore the right hand side for external?
- Is there a way to present it nice? If so would this include BuckleScript FFI or only the native one?

I'm happy to contribute to a solution. First thing would be to identify the desired output.

<img width="775" alt="screenshot 2019-01-08 at 17 38 38" src="https://user-images.githubusercontent.com/223045/50846649-f4bf8300-136f-11e9-9c83-fc9356713ad3.png">

**Comment by ostera** [comment]
As I said in our prior conversation, I'm more than happy to walk you through the codebase and help you find the place were a refactor could happen. The more people are familiar with `odoc`, the better 🙌 

However, I don't think `odoc` should understand how BuckleScript encodes its external values because they are internal to BuckleScript. It's an unnecessary coupling of the tools. I have an idea of what a nicer integration could look like, but that might not be of interest here. Let's look at how `externals` get documented using OCaml.

I'll use `Lwt_unix`, in particular `lwt_bytes.mli` as an example. 

![screenshot 2019-01-08 at 18 17 14](https://user-images.githubusercontent.com/854222/50847410-cc388880-1371-11e9-8840-b9b9c5440292.png)

![screenshot 2019-01-08 at 18 16 54](https://user-images.githubusercontent.com/854222/50847420-d22e6980-1371-11e9-8be1-ff40327ada42.png)

For the C externals seen in Lwt, the output looks nicer, yes, but I have the impression that this is merely an accident of being used for symbol lookup during linking. I may be mistaken, and I'm sure @aantron, @trefis, or @dbuenzli can comment better to how/why the C externals happen in this way.

More often than not in OCaml I've seen people hide externals with a more idiomatic API, which to me just makes sense as the external becomes an implementation detail. 

/cc @bobzhang

**Comment by aantron** [comment]
Looks like the problem is that BuckleScript mangles its external declarations, and we would need to unmangle them if we want to display them.

However, the docs produced by odoc are supposed to present a signature to the reader, not an implementation, which makes me suspect we should render all externals the same way as other values, i.e.

```ocaml
let foo: string => reactElement;
```
