### ISSUE TITLE
Remove or reconsider <section>s, <header>s, <article>s

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#327]
See https://github.com/ocaml/odoc/issues/326#issuecomment-467455333.

**Comment by dbuenzli** [comment]
I think a structure here would be as mentioned before to have as few nesting as possible and allow main elements to be easily retargeted on the page geometry e.g. using CSS grid.

The main logical elements that can be distinguished in ocamldoc generated documentation is a global navigation bar (the "breadcrumbs"), a local navigation bar (the "toc"), a preamble and actual contents (everything after the preamble). The preamble is defined by:

* For an `mli`, anything before the first structure item or header. 
* For an `odoc` page, anything before the first header preceeded by content.

This can then be rendered to a toplevel div or article with basically the following structure:

```xml
<article> 
 <nav>...</nav> <--! breadcrumbs -->
 <header>...</header>   <--! module preamble !-->
 <nav>...</nav> <--! toc -->
 <div>...</div> <--! contents -->
</article>
```

In the preamble and contents part the mapping to the ocamldoc language should be straightfoward. `ocamldoc` paragraphs map to paragraphs, lists to lists, headers to headers etc, structure item to block elements; all at the same level nesting level

Structure items map to a block element which distinguish the item and its doc string as block elements as well. In the doc string block, the straightforward mapping to the ocamldoc language is maintained.

This structure closely maps the mental model exposed by ocamldoc to the writer and thus should minimizes the discrepancy between what the user writes and what she gets or expect.

**Comment by lpw25** [comment]
A couple of questions/suggestions: Shouldn't there be a `<main>` tag somewhere or do people not actually use those? I feel like there should be some semantic element for the grouping of an item and its attached documentation. Isn't it really it's own little `<article>` or `<section>`? Certainly merlin treats them as standalone articles when it displays them to users. Similarly our internal search engine has individual listings for the individual definitions.

**Comment by dbuenzli** [comment]
> 1. Shouldn't there be a `<main>` tag somewhere or do people not actually use those?

One thing is that `<main>` should not be used as a descendent of an `article` and there should be only one in the document so I think it's better not to use it in case you want to compose the `odoc` output with other markup (you'd also need to find something else for the toplevel element).

> 2\. I feel like there should be some semantic element for the grouping of an item and its attached documentation. Isn't it really it's own little `<article>` or `<section>`?

I would certainly not use `article` since it denotes content to be considered independent and that can be distributed separately. `<section>` rather a `div` could be an option, but well, to be honest unless you can unlock some accessibility feature that could all be properly classified `div`s to me...

**Comment by lpw25** [comment]
> but well, to be honest unless you can unlock some accessibility feature that could all be properly classified `div`s to me

I was more thinking of search engines than accessibility. My understanding is that the semantic tags are in large part for helping search engines to correctly classify things, and ideally search engines would be able to list individual items (e.g. a search for `List.map` should be able to have a link straight to the `List.map` element rather than just a link to `List` as is currently the case), I'm not sure whether adding a `<section>` tag would actually make that work though -- SEO is something I know almost nothing about.

**Comment by dbuenzli** [comment]
> I was more thinking of search engines than accessibility.

I see, I think you should rather look into [microformats](https://en.wikipedia.org/wiki/Microformat) for this. See also [this bit](https://developers.google.com/search/docs/guides/intro-structured-data) at google.

**Comment by dbuenzli** [comment]
@lpw25 speaking of microformats these days when I google for opam package names on duckduckgo it actually offers a direct snippet on how to install the package, I wonder were that comes from. 

Try for example https://duckduckgo.com/?q=caml-mode

**Comment by aantron** [comment]
Done by @Drup in #426.
