### ISSUE TITLE
Page references don't work as documented

### ISSUE THREAD

**Issue by vphantom** [ocaml/odoc#346]
Hello!  I'm using Dune v1.8.2 and Odoc v1.4.0.  Based on [Dune documentation](https://dune.readthedocs.io/en/latest/documentation.html) I have the following in my `dune` file:

```text
(documentation
	(mld_files :standard))
```

I have `index.mld` and `test23.mld`.  My attempts:

* Based on [Using odoc](https://github.com/ocaml/odoc/blob/master/src/odoc/using-odoc.mld) in `index.mld` I have attempted `{{!page-test23}Test page}` but it produces `<span class="xref-unresolved" title="unresolved reference to &quot;test23&quot;"><span>Test page</span></span>`.

* I tried an alternative `{{!page:test23} Test page}`  (`:` instead of `-`) with same results.

* Based on [ocamldoc specs](http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sec357) I tried `{!page:test23}` but it produces `<code>test23</code>`.

* A manual HTML anchor `{{: test23.html } Test page}` does produce `<a href="test23.html">Test page</a>` which does lead to that page.

I don't know what else to try.  The `page` keyword seems to be recognized, but I haven't found a syntax to actually use it.  Am I misreading something or have I stumbled on a bug? :thinking:

**Comment by dbuenzli** [comment]
> * {{!page-test23}Test page}

That is the right syntax and should work. Can you please post a minimal repro case somewhere ?

**Comment by vphantom** [comment]
No problem.  See attached: [odoc-page-link-bug.tar.gz](https://github.com/ocaml/odoc/files/3033559/odoc-page-link-bug.tar.gz)

**Comment by dbuenzli** [comment]
Thanks. This is an `odoc` driving problem. 

I tried with `odig` and I saw the same problem due to the fact that no library is installed (This is due to `html-deps` being [broken](https://github.com/ocaml/odoc/issues/290); I opened https://github.com/b0-system/odig/issues/50 with a suggested workaround if you want the details). 

Adding (and installing) a library to your project fixes the problem for `odig`, but as far as I can tell not for `dune`. I suggest you file an issue there (especially since I think they do not use the `*-dep`, `odoc` commands) with your repro case.
