### ISSUE TITLE
Set language in code blocks

### ISSUE THREAD

**Issue by ulrikstrid** [ocaml/odoc#380]
It would be nice if we could tell odoc that a particular code block is either OCaml or Reason. If there is a is a integrated mode where we can switch syntax on the future it would be nice to provide examples in both languages and be able to switch between them.

**Comment by trefis** [comment]
The previous version of odoc/octavius had documentation for the new syntax: https://ocaml-doc.github.io/octavius/syntax.html

I don't know if there have been much changes since, but you can probably start from there ([here is the mld](https://github.com/ocaml-doc/octavius/blob/master/src/syntax.mld)).

**Comment by dbuenzli** [comment]
Also related to https://github.com/ocaml/odoc/pull/303
