### ISSUE TITLE
Reference to constructor in module

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#447]
With the new model, the reference `M.Foo` doesn't resolve but `M.t.Foo` does.

```ocaml
module M : sig
  type t = Foo
end

(** {!constructor:M.Foo} {!constructor:M.t.Foo} *)
```

In `Paths_types`, constructor parent should be `parent` or a new `constructor_parent` instead of `datatype`.

Also, the type for references allows extension and exception constructors in `{!constructor:..}` references but won't resolve them.

**Comment by jonludlam** [comment]
Hmm, if we changed the identifier we wouldn't be able to link correctly as we wouldn't know which type the construct was in. I think the issue is probably that when we open the module containing the type declaration in `Env.open_signature` we should recurse into the type declarations at that point and add them to the env?

**Comment by Julow** [comment]
Constructors (and fields) are already added to the env (in `Env.add_type`). It should be easy to add the corresponding `TypeDecl` to constructors in the env (add a third argument to `Constructor` in `Component.Element`).

The current issue is in signatures (`Find`) and `Paths_types`.

**Comment by jonludlam** [comment]
I'm still not clear on what the issue is with Paths_types?

**Comment by Julow** [comment]
We just need to allow "signature | datatype" parents in constructor references.

**Comment by jonludlam** [comment]
Oh in the _references_! I was thinking of the identifiers :-)

**Comment by Julow** [comment]
This is in the next milestone.
