### ISSUE TITLE
Linking to exceptions in @raise

### ISSUE THREAD

**Issue by CraigFe** [ocaml/odoc#475]
Using Odoc master, it doesn't appear to be possible to link to an exception definition from a `@raise` tag:

```ocaml
exception Foo

val f : unit -> _
(** @raise {!Foo} *)

val g : unit -> _
(** @raise Foo *)
```

![image](https://user-images.githubusercontent.com/26125912/90752305-81b21880-e2d7-11ea-9c8d-68aded6b8150.png)

I'd expect the former to work, but the latter would be fine too. CC @Julow.

**Comment by Julow** [comment]
Same for `@return`, which is rendered as `returns`.
The word after `@raise` must be the path to (or name?) the exception, references are not parsed here.

It seems that the new model doesn't resolve tags yet.

**Comment by mndrix** [comment]
This issue still exists as of odoc 2.1.0. I'd like to work on fixing this issue, but so far I've failed to find where tag resolution should be implemented; `xref2/link.ml` maybe? Can anyone point me in the right direction? Thanks.

**Comment by Julow** [comment]
Yes this isn't implemented at all. The good place is `xref2/link.ml` indeed, starting from `comment_inline_element`. No other tags are resolved, that's why you couldn't find easily.

**Comment by sim642** [comment]
Looks like there hasn't been any progress by @mndrix, so I thought I might give it a shot myself. Studying the code pointer out by @Julow, I accidentally stumbled upon #827, which I hopefully fixed in #887.

Coming back to this issue, from what I understand, the `Raise` variant needs to be changed throughout odoc and odoc-parser such that its first component is something other than `string`. I'm not sure what the appropriate type would be though, because there's a range of possibilities with varying flexibility (and abusability):
* `Reference.t`
* `Reference of Reference.t * link_content`
* `inline_element`
* ...

Since the current plaintext (`string`) should still be supported, some variant would be required, maybe `[Word of string | Reference of Reference.t * link_content]` as a mix from `leaf_inline_element` and `inline_element`? Or possibly even a reference that may only be to an exception (if that's possible)?

**Comment by sim642** [comment]
> The parser don't handle references, instead they are parsed as a second step in Odoc, in `src/model/semantics.ml` by calling `Reference.parse`. The parser already took care of separating the first word after `@raise` from the rest, so no need to modify it.

`Reference.parse` takes a location argument though, so it seemed to me that the parser need to be modified to provide `string with_location` instead of just `string`. At least that's how it is in the normal `Reference` variant.

---
> `src/model/comment.ml` is not exactly the output of the parser and can be changed, this would make sense:
> 
> ```ocaml
>   | `Raise of Reference.Exception.t * nestable_block_element with_location list
> ```

Isn't there a matter of backwards compatibility here? Currently in all the written documentation any text may be used as the first word. Of course the intention is that it refers to an exception, but do we want any existing `@raise Foo` to be implicitly interpreted as `@raise {!Foo}` instead of preserving the existing behavior for all non-explicit references?

**Comment by Julow** [comment]
> Reference.parse takes a location argument though

Indeed, this is missing in the AST. Now is not a good time to modify the parser however because we made a release recently that is a breaking change for several projects (`ocamlformat` has been released already).
For now, we would need to compute the approximate location from the location of the whole tag element. This can be improved later, when we have planned to release the parser.

There's no compatibility problem, `Reference.parse` doesn't bother with the `{!..}` part, it takes the path inside it.
