### ISSUE TITLE
References to method in object types

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#525]
References to methods in object types are not working.

```ocaml
type t = < m : int >
class cl : object method m : int end
```

In this example, `cl.m` resolves but `t.m` doesn't.

**Comment by lpw25** [comment]
I think that one is intended behaviour. I don't think we allow any references to parts of type expressions.

**Comment by Drup** [comment]
Don't we allow references to fields of record types ?

**Comment by Julow** [comment]
Indeed, we only allow references to nominal things (constructors, record fields). We also disallow references to polymorphic variants constructors.
However, should we consider adding this feature ? For example, we have very big polymorphic variants that we create type aliases for, as if they were nominal: https://github.com/ocaml/odoc/blob/master/src/model/paths_types.ml

**Comment by lpw25** [comment]
Those are not type expressions, they are datatype definitions. That is an important distinction in OCaml, and currently it is where odoc draws the line about what may be referenced.

We could change where we draw the line about what is linkable, but that is a broader question than just whether to link to methods in objects. At one extreme you could allow linking to the `foo` method in:
```
type t = < foo : int > -> < bar : string >
```
as `t.right.bar`. At the other extreme you could ban references to class methods since there is no case where you ever refer to a class method directly in OCaml itself.

**Comment by yawaramin** [comment]
Today in function docstrings we have the `@param` tag to describe parameters, since we similarly can't refer to individual parameters. Perhaps we should have a `@method` tag for object methods? E.g.,

```ocaml
type t = < foo : int >
(** Blah.

    @method foo get the foo. *)
```

**Comment by Julow** [comment]
Let's leave this closed.
