### ISSUE TITLE
Documentation of odoc is bad

### ISSUE THREAD

**Issue by jonludlam** [ocaml/odoc#573]
Some considerable effort needs to be made to improve it.

**Comment by avsm** [comment]
Progress towards this in #571 to document the supported interfaces.

**Comment by kenichi-asai** [comment]
Is odoc documentation available somewhere now?  I want to know whether odoc supports custom tags found in ocamldoc (or any other way to produce documents in two languages), because it seems customs tags in ocamldoc are no longer developed: https://github.com/ocaml/ocaml/issues/6707

**Comment by Columbus240** [comment]
A concrete problem: odoc currently links to the syntax reference of ocamldoc, but doesn't accept precisely the same syntax. The differences should be explained somewhere (or be linked in the README if such a document already exists).

I found the following differences between the syntax reference and odoc v1.5.3:
* ocamldoc allows arbitrary heading levels, but odoc only allows levels from 0 to 5.
* odoc doesn't interpret target-specific formatting as ocamldoc did. Namely `{%latex: ...%}` throws a warning and instead of ignoring the contents of the braces, the contents are printed.

**Comment by jonludlam** [comment]
Fixed by #733. Or at least, the situation is better than it was!
