### ISSUE TITLE
Destructive substitution and @inline

### ISSUE THREAD

**Issue by xvw** [ocaml/odoc#657]
First of all, I would like to sincerely thank you for your work. Odoc is very pleasant to use and the output is truly beautiful.

I randomly discovered the @inline attribute for module includes and I'm facing a little frustration, am I missing something, is it not yet supported but in the pipeline or does it just not make sense?

> Feel free to close this ticket if the question is not relevant.

My question is quite simple: "**how to avoid duplication of types in case of multiple inclusion and destructive substitution?**" 

For example: 

```ocaml
module type PART_A_OF_MY_API = sig 
   type t 
   val my_first_function : t -> t -> int
end

module type PART_B_OF_MY_API = sig 
   type t 
   val my_second_function : int -> t -> t
end

module type FULL_API = sig 
   (** the type of my full API, repeated for documentation purposes*)
   type t 
   include PART_A_OF_MY_API  with type t := t
   (** @inline *)

  include PART_B_OF_MY_API  with type t := t
   (** @inline *)
end
```

Currently, by doing this, my `t' type is found 3 times in the `FULL_API' documentation. While this is not dramatic in absolute terms, I find that it can sometimes make reading the API documentation very complex, for example, if I have more than 2 inclusions.

Thank you in advance for your answers. Xavier.

**Comment by jonludlam** [comment]
This is fixed in master - though I note that we do seem to have broken inlining in some recent commits handling to do with handling signature docs. With a local fix for the inlining (that I will PR shortly) it currently looks like this on my machine:

<img width="803" alt="Screenshot 2021-04-06 at 10 15 29" src="https://user-images.githubusercontent.com/210963/113688266-0a43c480-96c1-11eb-801e-b50b9a53befc.png">

Is this what you are hoping for?

**Comment by xvw** [comment]
Yes, it is **exactly what I am hopping**. Thanks a lot!

**Comment by jonludlam** [comment]
My mistake, master isn't even broken :-)

**Comment by xvw** [comment]
Ah very nice! 
I can't wait for this to be updated on OPAM!
