### ISSUE TITLE
Module references are resolved correctly

### ISSUE THREAD

**Issue by bikallem** [ocaml/odoc#674]
I generated `ppxlib` - https://github.com/ocaml-ppx/ppxlib - docs with dune. However, I still see docs like below
![image](https://user-images.githubusercontent.com/315907/117638828-297bb900-b17b-11eb-988b-a16892fcae2b.png)
Isn't module references like `'a Ppxlib_ast__.Import.Location` be resolved to `Location` module? 

I am using the pinned `odoc`, i.e. running from `master`

**Comment by jonludlam** [comment]
This is because `dune build @doc` only handles documentation produced by the code inside the tree. In this particular case, `Location` and `Longident` are from the compiler, and thus outside of the tree. If you use `odig` to generate the docs you get the output you're expecting:

<img width="808" alt="Screenshot 2021-05-10 at 14 42 35" src="https://user-images.githubusercontent.com/210963/117668589-fd256400-b19d-11eb-9305-8fda7c0a2af3.png">
