### ISSUE TITLE
Wrong link in table of contents due to duplicate generated name

### ISSUE THREAD

**Issue by gadmm** [ocaml/odoc#701]
Consider the following example:
```
{1 Awesome feature}
{2 Example}
{2 Use-cases}
{1 More awesome feature}
{2 Example}
{2 Use-cases}
```
The table of contents will generate erroneous links to the second "Example" and "Use-cases" sections, because the generated html names are the same as the first ones (`example` and `use-cases`).

A workaround is to name the sections manually but the problem is not immediately noticable, it is tedious to fix by hand, and it keeps happening.

**Comment by Drup** [comment]
Hmm, you are absolutely correct.

Should we generate unique ids for all sections ? It makes manual linking quite more annoying. Another solution is to assume that top level sections are at least unique, and use that to disambiguate.

**Comment by bluddy** [comment]
Another option is to detect duplicates and append a number to them (_1 etc).

**Comment by jonludlam** [comment]
We discussed this issue in the last odoc dev meeting. The current plan is:

1) Make the table of contents work -  possibly, as @bluddy suggests, by appending something to the anchors to make them unique. This will only happen on the second and subsequent instances of an anchor, so the first will always have the 'standard' id.
2) Issue a warning if a reference resolves to an ambiguous label, and the reference will end up pointing at the first instance of the ambiguous label (because subsequent ones will be renamed).

**Comment by gadmm** [comment]
Nice for the quick response!
I don't know how odoc is implemented so I cannot comment at a technical level and I do not know if you already take this into account, but it would be nice to not break existing links:
- anchors specified by hand are never altered (so if the generated duplicate comes before, the one before should have something appended).
- if there is currently no ambiguity for a generated anchor name, then it is not altered.
