### ISSUE TITLE
Full lib path in mld file

### ISSUE THREAD

**Issue by ACoquereau** [ocaml/odoc#805]
I want to reference a type `t` from a module `B` in a module `A` documentation in a same package.

If i write `{!module-B.type-t}` in a `a.mli` file. The generated documentation include a correct link to my type `t`.

But if i try this in a `a.mld` file, the generated link is not correct. I need to add the full path of `Mylib` in the link : `{!Mylib.module-B.type-t}`.
I though adding my package in the dune file such as: `(documentation (package mylib))` would correct this but it does not. 

Is it intended that i need to specify my path lib for each of my link ? Is there a way to avoid that ?

**Comment by Julow** [comment]
That might be due to the way Dune "wraps" libraries.

A library named `Mylib` with modules `A` and `B` compiles to 3 modules:
- `Mylib`, which contains aliases to the other modules, `module A = Mylib__A`
- `Mylib__A`, from `a.ml`
- `Mylib__B`, from `b.ml`

That's the paths Odoc sees. Odoc has a `--open` flag that can be used to open the `Mylib` module and have the expected paths, however I can't find a way to pass it via Dune currently.

**Comment by Julow** [comment]
From Dune's point of view, I think that's expected. The documentation is not attached to the library but to the package, which might contains many libraries. The documentation should show the paths that exist outside of the library.

**Comment by Julow** [comment]
This is superseded by https://github.com/ocaml/odoc/issues/856 and https://github.com/ocaml/dune/issues/5770
