### ISSUE TITLE
How to get rid of the top-level index

### ISSUE THREAD

**Issue by kkshinkai** [ocaml/odoc#807]
This is the directory structure of the documentation generated with `dune build @doc`.

```
_build/default/_doc
  /_html
    /my-module
      /index.html
    /index.html   <-- I don't need this
    /highlight.pack.js
    /odoc.css
```

I want `/_html/my-module` but not `/_html` to be the root of my doc site. 

If I use the following command:

```shell
git checkout gh-pages
rsync -av _build/default/_doc/_html/my-module/ .
```

I will lost the `odoc.css` and `highlight.pack.js`, and there also will be a back button (`›› Up - my-module`) on the nav of the `my-module/index.html`.

However, the site of odoc itself seems to do the right thing:

```
https://ocaml.github.io/odoc
  /index.html <-- with no nav and back button
  /odoc.css
  /highlight.pack.js
```

What should I do?

**Comment by Julow** [comment]
The top-level `index.html` is actually generated by Dune ([here](https://github.com/ocaml/dune/blob/main/src/dune_rules/odoc.ml#L386)) and I don't think we can avoid it. But the extra directory level is added by Odoc and I don't think we can avoid it either.

The directory hierarchy looks like this:

```
highlight.pack.js
index.html # Generated by Dune, lists packages
odoc.css
<your package>/
  <Library>/ # Dune "wraps" the libraries, adds an extra level
    <Module>/ # Modules are generated into 'Module/index.html' instead of 'Module.html'
      index.html # Doc for Module
    index.html # Doc for Library, which is actually an ocaml module
  index.html # Either generated by Dune or compiled from 'index.mld'
  # other .mld pages are here
```

All the levels are useful but I agree it's annoying because the url is longer and repetitive, especially if your project contains 1 package and 1 library.

An idea to take advantage of it: overwrite the toplevel index and add a javascript redirection to the home page of the project (github).

**Comment by jonludlam** [comment]
You could also take a look at the driver that generates odoc's website: https://github.com/ocaml/odoc/blob/master/doc/driver.md - this is the actual source file the is executed (via mdx) to generate odoc's website. It can be adapted if you want something a bit more custom than Dune can produce.

**Comment by dbuenzli** [comment]
Given the thumbs  by @kkshinkai up on @Julow's comment, I don't think there's anything to do here. Feel free to comment if you had a more precise idea @kkshinkai. Meanwhile I think we can close this.
