### ISSUE TITLE
Provide more context when issuing error messages:

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#84]
Case in point `odig odoc uucp -v -v`: 

```
odig: [EXEC:50523] ['odoc' 'html' '-I'
                    '/Users/dbuenzli/.opam/4.05.0+rc1/var/cache/odig/cache/ocaml/'
                    '-o'
                    '/Users/dbuenzli/.opam/4.05.0+rc1/var/cache/odig/odoc'
                    '/Users/dbuenzli/.opam/4.05.0+rc1/var/cache/odig/cache/uucp/uucp.odoc']
It is disallowed to nest references.
```
Would be nice to know where and why this is happening (tried to look for a `{!` inside another one [here](https://github.com/dbuenzli/uucp/blob/master/src/uucp.mli) but couldn't find one).

**Comment by trefis** [comment]
The error message is not the best indeed. I will reword that particular instance to make it clearer, and will try to give some context although I don't have source locations anymore at this point so it might be a bit annoying (but I can at least display what the reference points to).

I'm pretty sure in your case the error appears because of the conjunction of these two lines:
1. [uucp.mli#L1546](https://github.com/dbuenzli/uucp/blob/master/src/uucp.mli#L1546)
2. [uucp.mli#L1558](https://github.com/dbuenzli/uucp/blob/master/src/uucp.mli#L1558)

Now that there is splicing of the section titles what you end up with is
```
{{!uchartype}Unicode characters (scalar values) as {!Uchar.t} values.}
```

**Comment by trefis** [comment]
(note that in cases like this particular one I probably want to simply not link to `Uchar.t` in the spliced text)

**Comment by aantron** [comment]
@dbuenzli Is this still an issue with current odoc? It should now be printing locations and more useful error messages.

**Comment by dbuenzli** [comment]
This seems to have been fixed. I don't know when though.
