### ISSUE TITLE
Dead link to `doc:` in the `opam` file

### ISSUE THREAD

**Issue by smondet** [ocaml/odoc#86]
It says https://ocaml-doc.github.com/odoc which 404s

**Comment by trefis** [comment]
Indeed.
I hope to fix this by putting some documentation up at some point...

**Comment by aantron** [comment]
The [current `opam` file](https://github.com/ocaml/odoc/blob/4c09575a5b25f4b224322f25d7867ce41fa4d032/odoc.opam) doesn't have a `doc` field anymore (since the repo merge a few months back), so closing this. The new docs will probably be a new `README`, at least at first (https://github.com/ocaml/odoc/issues/116#issuecomment-380814988), so that's probably what will end up in the `doc` field.
