### ISSUE TITLE
Could you actualize a dependecy on odoc-parser?

### ISSUE THREAD

**Issue by Kakadu** [ocaml/odoc#898]
I'm not sure what does it do, but a constraint <2.0  moves my packages to the past. Any chance we could fix odoc + odoc-parser to fit odoc-parser.0.2 ?

```
✗ opam install odoc                                                                                   4.14.0+flambda
The following actions will be performed:
  ↘ downgrade odoc-parser 2.0.0 to 1.0.1   [required by odoc]
  ↻ recompile ocamlbuild  0.14.1           [upstream or system changes]
  ∗ install   odoc        2.1.1
  ↘ downgrade ocamlformat 0.24.1 to 0.23.0 [uses odoc-parser]
  ↻ recompile topkg       1.0.5            [uses ocamlbuild]
===== ∗ 1   ↻ 2   ↘ 2 =====
Do you want to continue? [Y/n] 
```

I'm using opam's latest  versions

**Comment by Et7f3** [comment]
I don't think it is related to opam binary but more to opam-repository because we hit this bug with esy too https://discuss.ocaml.org/t/can-you-help-me-make-my-project-build/10451/12 so the problem is more with https://github.com/ocaml/opam-repository/blob/241c98c6bd475be55ad96ab4588176d1179bcab6/packages/odoc/odoc.2.1.1/opam#L26

**Comment by Julow** [comment]
`odoc-parser` exposes an AST and any change to it would break Odoc, it cannot possibly be compatible with different versions of it at the same time.
The parser was extracted into its own package to share it with other tools (ocamlformat, mdx) but I think this was a mistake due to this. The parser is tried to Odoc and both packages must be modified at the same time.

I suggest that the other tools start to vendor the source code of the parser. That will remove a constraint and allow them to patch them to suit their needs better (for example, OCamlformat would prefer to pass an `in_channel` instead of a string and Mdx needs more precise locations and informations about the concrete syntax).
OCamlformat is successfully doing this with OCaml's parser and I think that's a good idea.

To fix your issue immediately, you can use the [platform installer](https://github.com/tarides/ocaml-platform-installer/) which cache and install the tools in a less intrusive way. Nix is also a good way to install some tools (ocamlformat, ocp-indent) but not others (merlin, odoc).

**Comment by jonludlam** [comment]
Given that ocamlformat already vendors the ocaml parser, it doesn't seem a particularly big stretch to have it vendor odoc-parser too. I don't think it should diverge from upstream though, so if it needs an `in_channel` we should add that to upstream odoc-parser.

**Comment by gpetiot** [comment]
odoc-parser will now be vendored by ocamlformat starting from the next release (https://github.com/ocaml-ppx/ocamlformat/pull/2189).

**Comment by dbuenzli** [comment]
I suppose this can be closed.
