### ISSUE TITLE
Generate GNU info files

### ISSUE THREAD

**Issue by neubyi** [ocaml/odoc#93]
Navigating HTML files is less convenient for some people.
Some of those who find HTML files hard to navigate enjoy the [GNU info](https://en.wikipedia.org/wiki/Info_(Unix)) file format.
GNU info might be worth adding as an optional output format.

**Comment by dbuenzli** [comment]
Unfortunately ressources are limited and there is already a lot of work to do on the plumbing and HTML backend.

I think a good compromise here is to guarantee that `odoc` provides a good experience in text mode only browsers like the one you can find in emacs's `M-x eww` which provides a similar experience to `info` and report issues if that is not the case. 

So in order to focus the issue tracker a bit I'm closing this.
